### PR TITLE
Reset Castro::point_mass after starting from scratch

### PR DESCRIPTION
**Pull request by WeiqunZhang**
Austin,

I have partially implemented the feature.  There is a new file problem.cpp.  Currently, there are two hard wired numbers in that file.  You need to set them to appropriate values, either by hard wiring them, or call a function to read Chimera models.   But since I am not familiar with Chimera models.  I will leave that to you.

### CODE REVIEW

**Comment by WeiqunZhang** [comment]
You will also need the latest development branch.

**Comment by jaharris87** [comment]
So, am I understanding correctly that this routine computes (M_chimera(r) -
M_castro(r)) and stores it as the point_mass variable?

**Comment by WeiqunZhang** [comment]
Yes, that's correct.

**Comment by WeiqunZhang** [comment]
It updates both Fortran and C++ side.

For restart, one has to put the point_mass into inputs file.

**Comment by jaharris87** [comment]
Understood; I was just going through the process of trying to extract g(r)
from Castro, will this be similar to how you've calculated M(r)?

**Comment by WeiqunZhang** [comment]
Yes.  The new function is adapted from Gravity::make_radial_phi.

**Pull request merged**
